import { SortingType } from "./utility/modRowSorting";

const initialState = {
  currentPreset: {
    mods: [],
    name: "",
  },
  categories: [],
  lastSelectedPreset: null,
  presets: [],
  filter: "",
  alwaysEnabledMods: [],
  hiddenMods: [],
  saves: [],
  isOnboardingToRun: false,
  wasOnboardingEverRun: false,
  isDev: false,
  isAdmin: false,
  areThumbnailsEnabled: false,
  isClosedOnPlay: false,
  isAuthorEnabled: false,
  isMakeUnitsGeneralsEnabled: false,
  isScriptLoggingEnabled: false,
  isSkipIntroMoviesEnabled: false,
  isAutoStartCustomBattleEnabled: false,
  allMods: [],
  packsData: {},
  packCollisions: { packTableCollisions: [], packFileCollisions: [] },
  newMergedPacks: [],
  pathsOfReadPacks: [],
  appFolderPaths: { gamePath: "", contentFolder: "" },
  isSetAppFolderPathsDone: false,
  overwrittenDataPackedFiles: {},
  outdatedPackFiles: {},
  startArgs: [],
  currentTab: "mods",
  isCreateSteamCollectionOpen: false,
  isWH3Running: false,
  toasts: [],
  removedModsCategories: {},
  // before we make symbolic links in data queue those mods to be re-enabled
  dataModsToEnableByName: [],
  // if a enabled mod was removed it's possible it was updated, re-enabled it then
  removedModsData: [],
  modRowsSortingType: SortingType.Ordered,
  importedMods: [],
  availableLanguages: ["en"],
  currentLanguage: "en",
  packDataOverwrites: {},
  modBeingCustomized: undefined,
  customizableMods: {},
} as AppState;

export default initialState;
