import { SortingType } from "./utility/modRowSorting";

const initialState = {
  currentPreset: {
    mods: [],
    name: "",
  },
  categories: [],
  categoryColors: {},
  lastSelectedPreset: null,
  presets: [],
  filter: "",
  alwaysEnabledModNames: [],
  hiddenModNames: [],
  saves: [],
  isOnboardingToRun: false,
  hasConfigBeenRead: false,
  wasOnboardingEverRun: false,
  isDev: false,
  isAdmin: false,
  canCreateSymbolicLinks: false,
  areThumbnailsEnabled: true,
  isClosedOnPlay: false,
  workshopModStagingMode: "disabled",
  compressWorkshopModsOnStart: false,
  cleanUpWorkshopModStagingAfterGameExit: false,
  isUsingEnglishLocalizations: false,
  isAuthorEnabled: true,
  // A missing config means this is the manager's first run. Start with the two-pane mod list;
  // an existing config is applied afterward and keeps its saved value (including legacy false).
  isDualModListLayoutEnabled: true,
  modListDensity: "comfortable",
  isShowingDisabledModsLoadOrder: true,
  isModListCategoryViewEnabled: false,
  isPresetAuthorEnabled: false,
  arePresetThumbnailsEnabled: false,
  isCategoryAuthorEnabled: false,
  areCategoryThumbnailsEnabled: false,
  isMakeUnitsGeneralsEnabled: false,
  requestFolderPathsForGame: undefined,
  isScriptLoggingEnabled: false,
  isSkipIntroMoviesEnabled: false,
  isAutoStartCustomBattleEnabled: false,
  isChangingGameProcessPriority: false,
  isFeaturesForModdersEnabled: false,
  moddersPrefix: "",
  isRigidModelV2CompressionEnabled: true,
  compressModsOnUpload: true,
  nodeEditorFavorites: [],
  isCompatCheckingVanillaPacks: false,
  allMods: [],
  workshopInstallStatuses: {},
  workshopUpdateCheckResults: {},
  packsData: {},
  unsavedPacksData: {},
  deletedPackFilePaths: {},
  recentPackPaths: [],
  packCollisions: {
    packTableCollisions: [],
    packFileCollisions: [],
    missingTableReferences: {},
    uniqueIdsCollisions: {},
    scriptListenerCollisions: {},
    packFileAnalysisErrors: {},
    missingFileRefs: {},
  },
  packCollisionsCheckProgress: {
    currentIndex: -1,
    maxIndex: 0,
    firstPackName: "",
    secondPackName: "",
    type: "Files",
  },
  newMergedPacks: [],
  pathsOfReadPacks: [],
  appFolderPaths: {
    gamePath: "",
    contentFolder: "",
    dataFolder: "",
    customModFolders: [],
    modSourceOrder: ["data", "workshop"],
  },
  isSetAppFolderPathsDone: false,
  overwrittenDataPackedFiles: {},
  outdatedPackFiles: {},
  packOpenRequest: undefined,
  startArgs: [],
  currentTab: "mods",
  loadOrderRules: [],
  disabledModLoadOrderRules: [],
  loadOrderRuleDisabledPacks: [],
  modLoadOrderRules: {},
  loadOrderRulesResolution: { rules: [], conflicts: [], disabledRules: [], supersededRules: [] },
  hiddenMainWindowTabs: [],
  isVisualsSortByCultureEnabled: true,
  isVisualsHideDuplicatesEnabled: true,
  // New and pre-feature configs start with the single-unit model visualization.
  unitViewerMode: "visualize",
  unitViewerShowWireframe: true,
  unitViewerShowUnitCard: true,
  mapCampaignName: "wh3_main_combi",
  mapSelectedRegion: undefined,
  currentFlowFileReloadNonce: 0,
  isCreateSteamCollectionOpen: false,
  isImportSteamCollectionOpen: false,
  isPackSearcherOpen: false,
  isWH3Running: false,
  toasts: [],
  removedModsCategories: {},
  // before we make symbolic links in data queue those mods to be re-enabled
  dataModsToEnableByName: [],
  // if a enabled mod was removed it's possible it was updated, re-enabled it then
  removedModsData: [],
  modRowsSortingType: SortingType.Ordered,
  enabledModsPaneSortingType: SortingType.Ordered,
  importedMods: [],
  pendingUsedModsImport: undefined,
  availableLanguages: ["en"],
  packDataOverwrites: {},
  modBeingCustomized: undefined,
  customizableMods: {},
  currentGame: "wh3",
  steamCollectionsToImport: {},
  isHelpOpen: false,
  lastModThatWasRead: undefined,
  currentlyReadingMod: undefined,
  isModTagPickerOpen: false,
  currentModToUpload: undefined,
  isLocalizingSubtypes: false,
  isShowingSkillNodeSetNames: false,
  hideRepeatedKeyPrefixes: true,
  isShowingHiddenSkills: true,
  isShowingHiddenModifiersInsideSkills: true,
  isCheckingSkillRequirements: true,
  skillTreesDisplayMode: "window",
  technologyTreesDisplayMode: "window",
  currentLocalization: {},
  userFlowOptions: {},

  // skills
  skillNodesToLevel: {},
  currentRank: 1,
} as AppState;

export default initialState;
