export const supportedGames = [
  "wh3",
  "wh2",
  "threeKingdoms",
  "attila",
  "troy",
  "pharaoh",
  "dynasties",
  "rome2",
] as const;
export type SupportedGames = (typeof supportedGames)[number];

export const supportedGameOptions = [
  "MakeUnitsGenerals",
  "SkipIntroMovies",
  "ScriptLogging",
  "AutoStartCustomBattle",
] as const;
export type SupportedGameOptions = (typeof supportedGameOptions)[number];

export const supportedGameOptionToStartGameOption: Record<
  SupportedGameOptions,
  keyof StartGameSpecificOptions
> = {
  MakeUnitsGenerals: "isMakeUnitsGeneralsEnabled",
  SkipIntroMovies: "isSkipIntroMoviesEnabled",
  ScriptLogging: "isScriptLoggingEnabled",
  AutoStartCustomBattle: "isAutoStartCustomBattleEnabled",
};

export const gameToGameFolder: Record<SupportedGames, string> = {
  wh2: "Total War WARHAMMER II",
  wh3: "Total War WARHAMMER III",
  threeKingdoms: "Total War Three Kingdoms",
  attila: "Total War Attila",
  troy: "Total War Troy",
  pharaoh: "Total War Pharaoh",
  dynasties: "Total War PHARAOH DYNASTIES",
  rome2: "Total War Rome II",
};

export const gameToGameName: Record<SupportedGames, string> = {
  wh2: "Warhammer 2",
  wh3: "Warhammer 3",
  threeKingdoms: "Three Kingdoms",
  attila: "Attila",
  troy: "Troy",
  pharaoh: "Pharaoh",
  dynasties: "Pharaoh Dynasties",
  rome2: "Rome 2",
};

export const gameToSteamId: Record<SupportedGames, string> = {
  wh2: "594570",
  wh3: "1142710",
  threeKingdoms: "779340",
  attila: "325610",
  troy: "1099410",
  pharaoh: "1937780",
  dynasties: "2951630",
  rome2: "214950",
};

export const gameToProcessName: Record<SupportedGames, string> = {
  wh2: "Warhammer2.exe",
  wh3: "Warhammer3.exe",
  threeKingdoms: "Three_Kingdoms.exe",
  attila: "Attila.exe",
  troy: "Troy.exe",
  pharaoh: "Pharaoh.exe",
  dynasties: "Pharaoh.exe",
  rome2: "Rome2.exe",
};

export const gameToAppDataFolderName: Record<SupportedGames, string> = {
  wh2: "Warhammer2",
  wh3: "Warhammer3",
  threeKingdoms: "ThreeKingdoms",
  attila: "Attila",
  troy: "Troy",
  pharaoh: "Pharaoh",
  dynasties: "PharaohDynasties",
  rome2: "Rome2",
};

export const gameToPackWithDBTablesName: Record<SupportedGames, string> = {
  wh2: "data.pack",
  wh3: "db.pack",
  threeKingdoms: "database.pack",
  attila: "data.pack",
  troy: "data.pack",
  pharaoh: "data.pack",
  dynasties: "data_db.pack",
  rome2: "data_rome2.pack",
};

export const gameToVanillaPacksData: Record<SupportedGames, { name: string }[]> = {
  wh2: [
    {
      name: "data.pack",
    },
  ],
  wh3: [
    {
      name: "data.pack",
    },
    { name: "db.pack" },
    { name: "data_script.pack" },
  ],
  threeKingdoms: [
    {
      name: "data.pack",
    },
    {
      name: "database.pack",
    },
  ],
  attila: [
    {
      name: "data.pack",
    },
  ],
  troy: [
    {
      name: "data.pack",
    },
  ],
  pharaoh: [
    {
      name: "data.pack",
    },
  ],
  dynasties: [
    {
      name: "data_db.pack",
    },
  ],
  rome2: [
    {
      name: "data_rome2.pack",
    },
  ],
};

export const vanillaPackNames: string[] = [];
for (const vanillaPacksData of Object.values(gameToVanillaPacksData)) {
  for (const vanillaPackData of vanillaPacksData) {
    if (!vanillaPackNames.includes(vanillaPackData.name)) vanillaPackNames.push(vanillaPackData.name);
  }
}

export const gameToIntroMovies: Record<SupportedGames, string[]> = {
  wh2: [
    // "movies\\startup_movie_01.ca_vp8",
    // "movies\\startup_movie_02.ca_vp8",
    // "movies\\startup_movie_03.ca_vp8",
  ],
  wh3: [
    "movies\\epilepsy_warning\\epilepsy_warning_en.ca_vp8",
    "movies\\gam_int.ca_vp8",
    "movies\\startup_movie_01.ca_vp8",
    "movies\\startup_movie_02.ca_vp8",
    "movies\\startup_movie_03.ca_vp8",
    "movies\\startup_movie_04.ca_vp8",
  ],
  threeKingdoms: ["movies\\startup_movie_01.ca_vp8", "movies\\startup_movie_02.ca_vp8"],
  attila: [],
  troy: [],
  pharaoh: [],
  dynasties: [],
  rome2: [],
};

export const gameToSupportedGameOptions: Record<SupportedGames, SupportedGameOptions[]> = {
  wh2: ["ScriptLogging"],
  wh3: ["MakeUnitsGenerals", "SkipIntroMovies", "ScriptLogging", "AutoStartCustomBattle"],
  threeKingdoms: ["SkipIntroMovies", "ScriptLogging"],
  attila: ["ScriptLogging"],
  troy: ["ScriptLogging"],
  pharaoh: ["ScriptLogging"],
  dynasties: ["ScriptLogging"],
  rome2: [],
};

export const gameToManifest: Record<SupportedGames, string[] | undefined> = {
  wh3: [
    "audio_base.pack",
    "audio_base_2.pack",
    "audio_base_bl.pack",
    "audio_base_m.pack",
    "audio_cn.pack",
    "audio_cn_2.pack",
    "audio_cn_bm.pack",
    "audio_cn_br.pack",
    "audio_cn_cst.pack",
    "audio_cn_lu.pack",
    "audio_cn_lu2.pack",
    "audio_cn_sc.pack",
    "audio_cn_tk.pack",
    "audio_cn_we.pack",
    "audio_en.pack",
    "audio_en_2.pack",
    "audio_en_bm.pack",
    "audio_en_br.pack",
    "audio_en_cst.pack",
    "audio_en_lu.pack",
    "audio_en_lu2.pack",
    "audio_en_pw.pack",
    "audio_en_sc.pack",
    "audio_en_tk.pack",
    "audio_en_we.pack",
    "audio_fr.pack",
    "audio_fr_2.pack",
    "audio_fr_bm.pack",
    "audio_fr_br.pack",
    "audio_fr_cst.pack",
    "audio_fr_lu.pack",
    "audio_fr_lu2.pack",
    "audio_fr_sc.pack",
    "audio_fr_tk.pack",
    "audio_fr_we.pack",
    "audio_ge.pack",
    "audio_ge_2.pack",
    "audio_ge_bm.pack",
    "audio_ge_br.pack",
    "audio_ge_cst.pack",
    "audio_ge_lu.pack",
    "audio_ge_lu2.pack",
    "audio_ge_sc.pack",
    "audio_ge_tk.pack",
    "audio_ge_we.pack",
    "audio_it.pack",
    "audio_it_2.pack",
    "audio_it_bm.pack",
    "audio_it_br.pack",
    "audio_it_cst.pack",
    "audio_it_lu.pack",
    "audio_it_lu2.pack",
    "audio_it_sc.pack",
    "audio_it_tk.pack",
    "audio_it_we.pack",
    "audio_pl.pack",
    "audio_pl_2.pack",
    "audio_pl_bm.pack",
    "audio_pl_br.pack",
    "audio_pl_cst.pack",
    "audio_pl_lu.pack",
    "audio_pl_lu2.pack",
    "audio_pl_sc.pack",
    "audio_pl_tk.pack",
    "audio_pl_we.pack",
    "audio_ru.pack",
    "audio_ru_2.pack",
    "audio_ru_bm.pack",
    "audio_ru_br.pack",
    "audio_ru_cst.pack",
    "audio_ru_lu.pack",
    "audio_ru_lu2.pack",
    "audio_ru_sc.pack",
    "audio_ru_tk.pack",
    "audio_ru_we.pack",
    "audio_sp.pack",
    "audio_sp_2.pack",
    "audio_sp_bm.pack",
    "audio_sp_br.pack",
    "audio_sp_cst.pack",
    "audio_sp_lu.pack",
    "audio_sp_lu2.pack",
    "audio_sp_sc.pack",
    "audio_sp_tk.pack",
    "audio_sp_we.pack",
    "boot.pack",
    "data.pack",
    "data_1.pack",
    "data_2.pack",
    "data_3.pack",
    "data_bl.pack",
    "data_bm.pack",
    "data_tk.pack",
    "data_we.pack",
    "data_wp_.pack",
    "data_script.pack",
    "data_script_3.pack",
    "db.pack",
    "local_br.pack",
    "local_br_3.pack",
    "local_cn.pack",
    "local_cn_3.pack",
    "local_cz.pack",
    "local_cz_3.pack",
    "local_en.pack",
    "local_en_3.pack",
    "local_fr.pack",
    "local_fr_3.pack",
    "local_ge.pack",
    "local_ge_3.pack",
    "local_it.pack",
    "local_it_3.pack",
    "local_kr.pack",
    "local_kr_3.pack",
    "local_pl.pack",
    "local_pl_3.pack",
    "local_ru.pack",
    "local_ru_3.pack",
    "local_sp.pack",
    "local_sp_3.pack",
    "local_tr.pack",
    "local_tr_3.pack",
    "local_zh.pack",
    "local_zh_3.pack",
    "models.pack",
    "models_2.pack",
    "models_3.pack",
    "models2.pack",
    "models2_2.pack",
    "models2_3.pack",
    "movies.pack",
    "movies_3.pack",
    "shaders.pack",
    "shaders_bl.pack",
    "terrain.pack",
    "terrain_2.pack",
    "terrain_3.pack",
    "terrain10.pack",
    "terrain10_2.pack",
    "terrain10_3.pack",
    "terrain11.pack",
    "terrain11_2.pack",
    "terrain13.pack",
    "terrain13_3.pack",
    "terrain2.pack",
    "terrain2_2.pack",
    "terrain2_3.pack",
    "terrain3.pack",
    "terrain3_2.pack",
    "terrain3_3.pack",
    "terrain4.pack",
    "terrain5.pack",
    "terrain5_3.pack",
    "terrain6.pack",
    "terrain6_3.pack",
    "terrain7.pack",
    "terrain7_3.pack",
    "terrain8.pack",
    "terrain9.pack",
    "terrain9_3.pack",
    "variants.pack",
    "variants_2.pack",
    "variants_3.pack",
    "variants_bl.pack",
    "variants_dds.pack",
    "variants_dds_3.pack",
    "variants_dds_bl.pack",
    "variants_dds2.pack",
    "variants_dds2_3.pack",
    "warmachines.pack",
    "warmachines_3.pack",
  ],
  troy: undefined,
  pharaoh: undefined,
  wh2: [
    "audio_base.pack",
    "audio_base_2.pack",
    "audio_base_bl.pack",
    "audio_base_bm.pack",
    "audio_base_br.pack",
    "audio_base_cst.pack",
    "audio_base_gc.pack",
    "audio_base_m.pack",
    "audio_base_tk.pack",
    "audio_base_we.pack",
    "audio_en.pack",
    "audio_en_2.pack",
    "audio_en_bm.pack",
    "audio_en_br.pack",
    "audio_en_cst.pack",
    "audio_en_tk.pack",
    "audio_en_we.pack",
    "audio_fr.pack",
    "audio_fr_2.pack",
    "audio_fr_bm.pack",
    "audio_fr_br.pack",
    "audio_fr_cst.pack",
    "audio_fr_tk.pack",
    "audio_fr_we.pack",
    "audio_ge.pack",
    "audio_ge_2.pack",
    "audio_ge_bm.pack",
    "audio_ge_br.pack",
    "audio_ge_cst.pack",
    "audio_ge_tk.pack",
    "audio_ge_we.pack",
    "audio_it.pack",
    "audio_it_2.pack",
    "audio_it_bm.pack",
    "audio_it_br.pack",
    "audio_it_cst.pack",
    "audio_it_tk.pack",
    "audio_it_we.pack",
    "audio_pl.pack",
    "audio_pl_2.pack",
    "audio_pl_bm.pack",
    "audio_pl_br.pack",
    "audio_pl_cst.pack",
    "audio_pl_tk.pack",
    "audio_pl_we.pack",
    "audio_ru.pack",
    "audio_ru_2.pack",
    "audio_ru_bm.pack",
    "audio_ru_br.pack",
    "audio_ru_cst.pack",
    "audio_ru_tk.pack",
    "audio_ru_we.pack",
    "audio_sp.pack",
    "audio_sp_2.pack",
    "audio_sp_bm.pack",
    "audio_sp_br.pack",
    "audio_sp_cst.pack",
    "audio_sp_tk.pack",
    "audio_sp_we.pack",
    "boot.pack",
    "campaign_variants.pack",
    "campaign_variants_2.pack",
    "campaign_variants_bl.pack",
    "campaign_variants_pro09_.pack",
    "campaign_variants_sb.pack",
    "campaign_variants_sf.pack",
    "campaign_variants_twa02_.pack",
    "campaign_variants_wp_.pack",
    "data.pack",
    "data_1.pack",
    "data_2.pack",
    "data_bl.pack",
    "data_bm.pack",
    "data_gc.pack",
    "data_hb.pack",
    "data_pro09_.pack",
    "data_pw.pack",
    "data_sb.pack",
    "data_sc.pack",
    "data_sf.pack",
    "data_tk.pack",
    "data_twa01_.pack",
    "data_twa02_.pack",
    "data_we.pack",
    "data_wp_.pack",
    "local_br.pack",
    "local_br_2.pack",
    "local_br_gc.pack",
    "local_cn.pack",
    "local_cn_2.pack",
    "local_cn_gc.pack",
    "local_cz.pack",
    "local_cz_2.pack",
    "local_cz_gc.pack",
    "local_en.pack",
    "local_en_2.pack",
    "local_en_gc.pack",
    "local_fr.pack",
    "local_fr_2.pack",
    "local_fr_gc.pack",
    "local_ge.pack",
    "local_ge_2.pack",
    "local_ge_gc.pack",
    "local_it.pack",
    "local_it_2.pack",
    "local_it_gc.pack",
    "local_kr.pack",
    "local_kr_2.pack",
    "local_kr_gc.pack",
    "local_pl.pack",
    "local_pl_2.pack",
    "local_pl_gc.pack",
    "local_ru.pack",
    "local_ru_2.pack",
    "local_ru_gc.pack",
    "local_sp.pack",
    "local_sp_2.pack",
    "local_sp_gc.pack",
    "local_tr.pack",
    "local_tr_2.pack",
    "local_tr_gc.pack",
    "local_zh.pack",
    "local_zh_2.pack",
    "local_zh_gc.pack",
    "models.pack",
    "models_2.pack",
    "models_gc.pack",
    "models2.pack",
    "models2_2.pack",
    "models2_gc.pack",
    "movies.pack",
    "movies_2.pack",
    "movies_sf.pack",
    "movies2.pack",
    "movies3.pack",
    "shaders.pack",
    "shaders_bl.pack",
    "terrain.pack",
    "terrain_2.pack",
    "terrain_gc.pack",
    "terrain2.pack",
    "terrain2_2.pack",
    "terrain2_gc.pack",
    "terrain3.pack",
    "terrain3_2.pack",
    "terrain3_gc.pack",
    "terrain4.pack",
    "terrain4_2.pack",
    "terrain5.pack",
    "terrain7.pack",
    "terrain7_2.pack",
    "terrain7_gc.pack",
    "terrain8.pack",
    "terrain8_2.pack",
    "terrain9.pack",
    "variants.pack",
    "variants_2.pack",
    "variants_bl.pack",
    "variants_gc.pack",
    "variants_hb.pack",
    "variants_sb.pack",
    "variants_sc.pack",
    "variants_sf.pack",
    "variants_wp_.pack",
    "variants_dds.pack",
    "variants_dds_2.pack",
    "variants_dds_bl.pack",
    "variants_dds_gc.pack",
    "variants_dds_sb.pack",
    "variants_dds_sf.pack",
    "variants_dds_wp_.pack",
    "variants_dds2.pack",
    "variants_dds2_2.pack",
    "variants_dds2_sb.pack",
    "variants_dds2_sc.pack",
    "variants_dds2_sf.pack",
    "variants_dds2_wp_.pack",
    "warmachines.pack",
    "warmachines_2.pack",
    "warmachines_hb.pack",
  ],
  threeKingdoms: [
    "audio.pack",
    "boot.pack",
    "data.pack",
    "data_dlc06.pack",
    "data_ep.pack",
    "data_mh.pack",
    "database.pack",
    "fast.pack",
    "language.txt",
    "local_br.pack",
    "local_cn.pack",
    "local_cz.pack",
    "local_en.pack",
    "local_fr.pack",
    "local_ge.pack",
    "local_it.pack",
    "local_kr.pack",
    "local_pl.pack",
    "local_ru.pack",
    "local_sp.pack",
    "local_tr.pack",
    "local_zh.pack",
    "models.pack",
    "models2.pack",
    "movies.pack",
    "movies_dlc06.pack",
    "movies_ep.pack",
    "movies_mh.pack",
    "movies_wb.pack",
    "movies2.pack",
    "shaders.pack",
    "terrain.pack",
    "terrain2.pack",
    "terrain3.pack",
    "terrain4.pack",
    "terrain5.pack",
    "variants.pack",
    "variants_dds.pack",
    "vegetation.pack",
  ],
  attila: [
    "boot.pack",
    "charlemagne.pack",
    "music_en_shared_rome2.pack",
    "local_en_shared_rome2.pack",
    "local_en.pack",
    "tiles4.pack",
    "tiles3.pack",
    "tiles2.pack",
    "tiles.pack",
    "terrain2.pack",
    "terrain.pack",
    "sound.pack",
    "slavs.pack",
    "music.pack",
    "movies.pack",
    "models3.pack",
    "models2.pack",
    "models.pack",
    "data.pack",
  ],
  dynasties: [
    "audio.pack",
    "audio_cn.pack",
    "audio_en.pack",
    "audio_fr.pack",
    "audio_ge.pack",
    "audio_it.pack",
    "audio_m.pack",
    "audio_pl.pack",
    "audio_sp.pack",
    "boot.pack",
    "chariot.pack",
    "data.pack",
    "data_bl.pack",
    "data_db.pack",
    "data_special.pack",
    "local_br.pack",
    "local_cn.pack",
    "local_cz.pack",
    "local_en.pack",
    "local_fr.pack",
    "local_ge.pack",
    "local_it.pack",
    "local_kr.pack",
    "local_pl.pack",
    "local_sp.pack",
    "local_tr.pack",
    "local_zh.pack",
    "models.pack",
    "movies.pack",
    "shaders.pack",
    "shaders_bl.pack",
    "terrain.pack",
    "terrain2.pack",
    "terrain3.pack",
    "terrain4.pack",
    "ui.pack",
    "units.pack",
    "variants.pack",
    "variants2.pack",
  ],
  rome2: [
    "sound.pack",
    "data.pack",
    "terrain.pack",
    "tiles4.pack",
    "tiles2_rome2.pack",
    "tiles2.pack",
    "movies.pack",
    "tiles3.pack",
    "local_en.pack",
    "music_en_shared_rome2.pack",
    "tiles4_rome2.pack",
    "music.pack",
    "terrain2.pack",
    "local_en_shared_rome2.pack",
    "boot.pack",
    "data_rome2.pack",
    "models_rome2.pack",
    "models3_rome2.pack",
    "movies_rome2.pack",
    "terrain2_rome2.pack",
    "models.pack",
    "music_rome2.pack",
    "models2.pack",
    "tiles.pack",
    "tiles_rome2.pack",
    "terrain3_rome2.pack",
    "tiles3_rome2.pack",
    "sound_rome2.pack",
    "divided.pack",
    "invasion.pack",
    "models2_rome2.pack",
    "terrain_rome2.pack",
    "gaul.pack",
    "blood_rome2.pack",
    "punic.pack",
  ],
};

export const SupportedLanguages = ["en", "fr", "de", "es", "ru", "pl", "pt", "tr", "zh", "ja", "ko"] as const;
type typedSupportedLanguagesList = typeof SupportedLanguages;
export type SupportedLanguage = typedSupportedLanguagesList[number]; // this compiles to 'circle' | 'square'
